version: '3.1'
services:
  db:
    container_name: omop
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
    - ./:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: omop

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080